[build-system]
requires = ["setuptools>=43.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "ghchangelist"
version = "0.1"
requires-python = ">=3.9"
readme = "README.md"
license = {file = "LICENSE"}
classifiers = [
  "Development Status :: 3 - Alpha",
  "License :: OSI Approved :: BSD License",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3 :: Only",
]

dependencies = [
    "requests",
    "requests-cache",
    "tqdm",
    "PyGithub",
]

[project.urls]
"Source" = "https://github.com/lagru/ghchangelist"

[project.scripts]
ghchangelist = "ghchangelist.__main__:main"
